name: sarkargar
description: اولین اپلیکیشن استخدام کارگر روزمزد در ایران

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  fluttertoast: ^8.0.9
  dio: ^4.0.6
  font_awesome_flutter: ^10.1.0
  digit_to_persian_word: ^2.0.0
  im_stepper: ^1.0.1+1
  lottie: ^1.3.0
  flutter_native_splash: ^2.2.4
  restart_app: ^1.1.0
  iconsax: ^0.0.8
  geolocator: ^9.0.1
  url_launcher: ^6.1.5
  image_picker: ^0.8.5+3
  equatable: ^2.0.3
  cached_network_image: ^3.2.1
  toggle_switch: ^2.0.1
  flutter_switch: ^0.3.2
  flutter_map: ^0.14.0
  latlong2: ^0.8.1
  get: ^4.6.5
  flutter_map_marker_cluster: ^0.4.4
  syncfusion_flutter_maps: ^20.2.43
  photo_view: ^0.14.0
  get_storage: ^2.0.3
  maps_launcher: ^2.0.1
  flutter_multi_slider: ^1.1.0
  animations: ^2.0.4
  flutter_staggered_animations:
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/lottie/
    - assets/SVG/

  fonts:
    - family: sans
      fonts:
        - asset: assets/fonts/samim.ttf
    - family: titr
      fonts:
        - asset: assets/fonts/titr.ttf

