class AdvModel {
  final String id,
      advertizerId,
      adType,
      title,
      category,
      city,
      descs,
      gender,
      workType,
      workTime,
      payMethod,
      profission,
      price,
      callNumber,
      smsNumber,
      emailAddress,
      websiteAddress,
      instagramid,
      telegramId,
      whatsappNumber,
      time,
      address;
  final double lat, lon;

  final bool resumeBool,
      callBool,
      smsBool,
      chatBool,
      emailBool,
      websiteBool,
      instagramBool,
      telegramBool,
      whatsappBool,
      locationBool;

  AdvModel(
      this.callNumber,
      this.smsNumber,
      this.emailAddress,
      this.websiteAddress,
      this.instagramid,
      this.telegramId,
      this.whatsappNumber,
      this.lat,
      this.lon,
      this.time,
      this.resumeBool,
      this.callBool,
      this.smsBool,
      this.chatBool,
      this.emailBool,
      this.websiteBool,
      this.instagramBool,
      this.telegramBool,
      this.whatsappBool,
      this.locationBool,
      this.profission,
      this.price,
      this.address,
      this.id,
      this.advertizerId,
      this.adType,
      this.title,
      this.category,
      this.city,
      this.descs,
      this.gender,
      this.workType,
      this.workTime,
      this.payMethod);

  AdvModel.fromJson(Map<dynamic, dynamic> json)
      : id = json['id'],
        advertizerId = json['advertizerid'],
        adType = json['adtype'],
        title = json['title'],
        category = json['category'],
        city = json['city'],
        descs = json['descs'],
        gender = json['gender'],
        workType = json['workType'],
        workTime = json['workTime'],
        payMethod = json['payMethod'],
        profission = json['profission'],
        price = json['price'],
        address = json['address'],
        resumeBool = json['resumeBool'] == '1' ? true : false,
        callBool = json['callBool'] == '1' ? true : false,
        smsBool = json['smsbool'] == '1' ? true : false,
        chatBool = json['chatbool'] == '1' ? true : false,
        emailBool = json['emailBool'] == '1' ? true : false,
        websiteBool = json['websiteBool'] == '1' ? true : false,
        instagramBool = json['instagramBool'] == '1' ? true : false,
        telegramBool = json['telegramBool'] == '1' ? true : false,
        whatsappBool = json['whatsappBool'] == '1' ? true : false,
        locationBool = json['locationbool'] == '1' ? true : false,
        callNumber = json['callNumber'],
        smsNumber = json['smsNumber'],
        emailAddress = json['emailAddress'],
        websiteAddress = json['websiteAddress'],
        instagramid = json['instagramid'],
        telegramId = json['telegramId'],
        whatsappNumber = json['whatsappNumber'],
        lat = double.parse(json['locationlat']),
        lon = double.parse(json['locationlon']),
        time = json['time'];
}
